# Generated by Django 5.1 on 2024-08-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_category_news_ncategory_alter_news_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='ncategory',
            new_name='category',
        ),
    ]
